### ISSUE TITLE
Grammar bit

### ISSUE THREAD

**Issue by littledan** [rbuckton/proposal-throw-expressions#1]
Presumably, when you integrate this into the main spec, you'll have to extend the no-lookahead rule to ExpressionStatement to prohibit throw expressions as an ExpressionStatement, right? Otherwise, there's an ambiguity.

**Comment by rbuckton** [comment]
I was thinking of just moving ThrowStatement before ExpressionStatement in the Statement production. This is similar to how Block is parsed before we consider parsing ObjectLiteralExpression.

**Comment by littledan** [comment]
The grammar isn't ordered like this--it's supposed to be unambiguous even if you take all the possible paths. (The exception is RegExp Annex B.) [ExpressionStatement](https://tc39.github.io/ecma262/#prod-ExpressionStatement) has a lookahead prohibition for `{` which is how that's implemented.

**Comment by rbuckton** [comment]
Ah, I see. Thank you for the clarification. I'll update the grammar section.

**Comment by rbuckton** [comment]
Fixed by 4d7ec522ff4105f75c1f6358e9c8f66f4d46591a

**Comment by littledan** [comment]
LGTM

**Comment by chharvey** [comment]
I have the same question as @rbuckton. Any reason why `ThrowStatement` can’t just be deleted? Then you wouldn’t need to have `throw` in the set of forbidden lookaheads of `ExpressionStatement`.
