### ISSUE TITLE
Consider ** operator style parens

### ISSUE THREAD

**Issue by bmeck** [rbuckton/proposal-throw-expressions#2]
like @erights said, it might be prudent to enforce ambiguous cases declare the proper interpetation by mandating parentheses

**Comment by rbuckton** [comment]
I don't think parentheses are strictly necessary. Based on #3, I've chosen to give the `throw` operator the same precedence as `delete` and `void`. This fits well given the primary motivations are expressions like: 

```js
x = choice === "a" ? a() : 
    choice === "b" ? b() : 
    throw new Error("Argument out of range");

x = o?.x ?? throw new Error("Invalid option");
```
