### ISSUE TITLE
Proposed example doesn't work with proposed grammar

### ISSUE THREAD

**Issue by waldemarhorwat** [rbuckton/proposal-throw-expressions#3]
The proposal lists an example use of a throw expression in a logical operation as:

`this._id = value || throw new Error("Invalid value");`

This doesn't work because `||` has higher precedence than `throw` in the grammar, so you'd need to write it like this:

`this._id = value || (throw new Error("Invalid value"));`

Which one is correct? The example in the proposal or the grammar in the proposal?

**Comment by rbuckton** [comment]
Hmm. I intended it for it to have the same precedence as `yield` does today, so you are correct that the example is wrong. However, I may need to revise the precedence depending on what the operator precedence of `??` is as I'd definitely like to be able to parse `this._id = value ?? throw new Error()` without needing parens.

**Comment by rbuckton** [comment]
It may be that it needs to be _UnaryExpression_ to support `||` (or `??`, though that proposal does not specify precedence yet).

Given:
```js
a ? throw b ? c : d : e
```

Under the current proposal the above means:
```js
a ? (throw (b ? c : d)) : e
```

However, changing to _UnaryExpression_ would result in the following interpretation:
```js
a ? ((throw b) ? c : d) : e
```
