### ISSUE TITLE
[Question] Return value?

### ISSUE THREAD

**Issue by brn** [rbuckton/proposal-throw-expressions#5]
Hey.
This proposal is almost looks good for ecmascript.
But I have question about return value of throw expression that catched by try-catch statement. 

e.g.

```javascript
let thrownValue = null;
try {
  thrownValue = throw new Error('Error');
} catch(e) {
  // thrownValue === null?
}
```

In above case, thrownValue become null or other intermediate value?
I think thrownValue should become Error object.

**Comment by rbuckton** [comment]
It would be `null`, which is no different than if you wrote:
```js
let thrownValue = null;
try {
  thrownValue = (() => { throw new Error('Error'); })();
}
catch (e) {
}
```

**Comment by brn** [comment]
Thank you.
I could understand by your example.
