### ISSUE TITLE
Cohesion/coherency between statements turning into expressions?

### ISSUE THREAD

**Issue by samuelgoto** [rbuckton/proposal-throw-expressions#6]
One of the action items that we took as a group in the last meeting (todo(goto): link notes) was to ratioanalize the patterns/principles around turning more of the other statements into expressions. Can you help me understand how throw expressions fit into the bigger trend to turn statements into expressions?

For example, how does this relate to ```do``` expressions? Would ```for``` ever become an expression and if so what principles/patterns would it follow from ```throw``` expressions? Should ```try``` be an expression? Can we enumerate the things we have in mind? In the context of the trend to move dom construction into JS (e.g. JSX) what are the ergonomics wins/losses? Are there other applications we expect this stream of work to be useful?

**Comment by rbuckton** [comment]
See #4 for this proposal's relationship to `do` expressions, as well as https://github.com/rbuckton/proposal-throw-expressions/issues/4#issuecomment-328692463 regarding turning other statements into expressions.
